services:
  # Infrastructure
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-orchestrator
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Core application (data flow services)
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: server
    depends_on:
      rabbitmq:
        condition: service_healthy
      year-filter-worker:
        condition: service_started
      time-filter-worker:
        condition: service_started
      amount-filter-worker:
        condition: service_started
      join-data-handler:
        condition: service_started
      itemid-join-worker:
        condition: service_started
      storeid-join-worker:
        condition: service_started
      in-file-join-worker:
        condition: service_started
      query2-map-worker:
        condition: service_started
      query2-reduce-s2-2023:
        condition: service_started
      query2-reduce-s1-2024:
        condition: service_started
      query2-reduce-s2-2024:
        condition: service_started
      query2-reduce-s1-2025:
        condition: service_started
      query2-reduce-s2-2025:
        condition: service_started
      query3-map-worker:
        condition: service_started
      query3-reduce-s2-2023:
        condition: service_started
      query3-reduce-s1-2024:
        condition: service_started
      query3-reduce-s2-2024:
        condition: service_started
      query3-reduce-s1-2025:
        condition: service_started
      query3-reduce-s2-2025:
        condition: service_started
      query4-map-worker:
        condition: service_started
      query4-reduce-worker:
        condition: service_started
      streaming-service:
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=password
    profiles: ["data-flow"]

  client-1:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: client
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    environment:
      - CLIENT_ID=CLI1
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=password
    command: ["./main", "/app/data"]
    profiles: ["data-flow"]

  client-2:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: client-2
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    environment:
      - CLIENT_ID=CLI2
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=password
    command: ["./main", "/app/data"]
    profiles: ["data-flow"]

  # Worker services
  year-filter-worker:
    build:
      context: .
      dockerfile: ./workers/filter/year-filter/Dockerfile
    container_name: year-filter-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    profiles: ["orchestration"]

  time-filter-worker:
    build:
      context: .
      dockerfile: ./workers/filter/time-filter/Dockerfile
    container_name: time-filter-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    profiles: ["orchestration"]

  amount-filter-worker:
    build:
      context: .
      dockerfile: ./workers/filter/amount-filter/Dockerfile
    container_name: amount-filter-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    profiles: ["orchestration"]

  # Join Data Handler
  join-data-handler:
    build:
      context: .
      dockerfile: ./workers/join/data-handler/Dockerfile
    container_name: join-data-handler
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    profiles: ["orchestration"]

  # ItemID Join Worker
  itemid-join-worker:
    build:
      context: .
      dockerfile: ./workers/join/in-memory/itemid/Dockerfile
    container_name: itemid-join-worker
    depends_on:
      join-data-handler:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    profiles: ["orchestration"]

  # StoreID Join Worker
  storeid-join-worker:
    build:
      context: .
      dockerfile: ./workers/join/in-memory/storeid/Dockerfile
    container_name: storeid-join-worker
    depends_on:
      join-data-handler:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    profiles: ["orchestration"]

  # In-File Join Worker (Query 4)
  in-file-join-worker:
    build:
      context: .
      dockerfile: ./workers/join/in-file/Dockerfile
    container_name: in-file-join-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      join-data-handler:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    volumes:
      - shared-data:/shared-data
    profiles: ["orchestration"]

  # Query 2 MapReduce Workers
  query2-map-worker:
    build:
      context: .
      dockerfile: ./workers/group_by/query2_mapreduce/map_worker/Dockerfile
    container_name: query2-map-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    profiles: ["orchestration"]

  query2-reduce-s2-2023:
    build:
      context: .
      dockerfile: ./workers/group_by/query2_mapreduce/reduce_workers/Dockerfile
    container_name: query2-reduce-s2-2023
    depends_on:
      rabbitmq:
        condition: service_healthy
      query2-map-worker:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    command: ["./reduce-worker-s2-2023"]
    profiles: ["orchestration"]

  query2-reduce-s1-2024:
    build:
      context: .
      dockerfile: ./workers/group_by/query2_mapreduce/reduce_workers/Dockerfile
    container_name: query2-reduce-s1-2024
    depends_on:
      rabbitmq:
        condition: service_healthy
      query2-map-worker:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    command: ["./reduce-worker-s1-2024"]
    profiles: ["orchestration"]

  query2-reduce-s2-2024:
    build:
      context: .
      dockerfile: ./workers/group_by/query2_mapreduce/reduce_workers/Dockerfile
    container_name: query2-reduce-s2-2024
    depends_on:
      rabbitmq:
        condition: service_healthy
      query2-map-worker:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    command: ["./reduce-worker-s2-2024"]
    profiles: ["orchestration"]

  query2-reduce-s1-2025:
    build:
      context: .
      dockerfile: ./workers/group_by/query2_mapreduce/reduce_workers/Dockerfile
    container_name: query2-reduce-s1-2025
    depends_on:
      rabbitmq:
        condition: service_healthy
      query2-map-worker:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    command: ["./reduce-worker-s1-2025"]
    profiles: ["orchestration"]

  query2-reduce-s2-2025:
    build:
      context: .
      dockerfile: ./workers/group_by/query2_mapreduce/reduce_workers/Dockerfile
    container_name: query2-reduce-s2-2025
    depends_on:
      rabbitmq:
        condition: service_healthy
      query2-map-worker:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    command: ["./reduce-worker-s2-2025"]
    profiles: ["orchestration"]

  # Query 3 MapReduce Workers
  query3-map-worker:
    build:
      context: .
      dockerfile: ./workers/group_by/query3_mapreduce/map_worker/Dockerfile
    container_name: query3-map-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    profiles: ["orchestration"]

  query3-reduce-s2-2023:
    build:
      context: .
      dockerfile: ./workers/group_by/query3_mapreduce/reduce_workers/Dockerfile
    container_name: query3-reduce-s2-2023
    depends_on:
      rabbitmq:
        condition: service_healthy
      query3-map-worker:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    command: ["./reduce-worker-s2-2023"]
    profiles: ["orchestration"]

  query3-reduce-s1-2024:
    build:
      context: .
      dockerfile: ./workers/group_by/query3_mapreduce/reduce_workers/Dockerfile
    container_name: query3-reduce-s1-2024
    depends_on:
      rabbitmq:
        condition: service_healthy
      query3-map-worker:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    command: ["./reduce-worker-s1-2024"]
    profiles: ["orchestration"]

  query3-reduce-s2-2024:
    build:
      context: .
      dockerfile: ./workers/group_by/query3_mapreduce/reduce_workers/Dockerfile
    container_name: query3-reduce-s2-2024
    depends_on:
      rabbitmq:
        condition: service_healthy
      query3-map-worker:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    command: ["./reduce-worker-s2-2024"]
    profiles: ["orchestration"]

  query3-reduce-s1-2025:
    build:
      context: .
      dockerfile: ./workers/group_by/query3_mapreduce/reduce_workers/Dockerfile
    container_name: query3-reduce-s1-2025
    depends_on:
      rabbitmq:
        condition: service_healthy
      query3-map-worker:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    command: ["./reduce-worker-s1-2025"]
    profiles: ["orchestration"]

  query3-reduce-s2-2025:
    build:
      context: .
      dockerfile: ./workers/group_by/query3_mapreduce/reduce_workers/Dockerfile
    container_name: query3-reduce-s2-2025
    depends_on:
      rabbitmq:
        condition: service_healthy
      query3-map-worker:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    command: ["./reduce-worker-s2-2025"]
    profiles: ["orchestration"]

  # Query 4 MapReduce Workers
  query4-map-worker:
    build:
      context: .
      dockerfile: ./workers/group_by/query4_mapreduce/map_worker/Dockerfile
    container_name: query4-map-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    profiles: ["orchestration"]

  query4-reduce-worker:
    build:
      context: .
      dockerfile: ./workers/group_by/query4_mapreduce/reduce_worker/Dockerfile
    container_name: query4-reduce-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      query4-map-worker:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    profiles: ["orchestration"]

  # Streaming service
  streaming-service:
    build:
      context: .
      dockerfile: ./stream/Dockerfile
    container_name: streaming-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    profiles: ["orchestration"]

  # Query gateway service
  query-gateway:
    build:
      context: .
      dockerfile: ./query-gateway/Dockerfile
    container_name: query-gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password
    profiles: ["orchestration"]

  # Testing (optional, can be run with profile)
  test-runner:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    container_name: test-runner
    profiles: ["test"]
    depends_on:
      rabbitmq:
        condition: service_healthy
      server:
        condition: service_started
    environment:
      RABBITMQ_URL: "amqp://admin:password@rabbitmq:5672/"
      LOG_LEVEL: "info"
      GOMAXPROCS: "1"
    command: ["go", "test", "-v", "./..."]
    stdin_open: true
    tty: true

volumes:
  shared-data:
    driver: local