services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: echo-server
    ports:
      - "8081:8080"   # TCP port for client connections
    networks:
      - echo-network
      - shared-network
    environment:
      - SERVER_PORT=8080
      - RABBITMQ_HOST=rabbitmq-orchestrator
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=password

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: echo-client
    depends_on:
      server:
        condition: service_started
    networks:
      - echo-network
    volumes:
      - ./input.txt:/app/input.txt
    command: ["./main", "/app/input.txt", "echo-server:8080"]

networks:
  echo-network:
    driver: bridge
  shared-network:
    external: true
