services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - echo-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: echo-server
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - echo-network

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: echo-client
    depends_on:
      rabbitmq:
        condition: service_healthy
      server:
        condition: service_started
    networks:
      - echo-network
    volumes:
      - ./input.txt:/app/input.txt
    command: ["./main", "/app/input.txt"]

networks:
  echo-network:
    driver: bridge
