services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-orchestrator
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - orchestrator-network
      - shared-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  query-orchestrator:
    build:
      context: ../../..
      dockerfile: ./server/controller/query-orchestrator/Dockerfile
    container_name: query-orchestrator
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - orchestrator-network
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password

  # Worker services
  filter-worker:
    build:
      context: ../../..
      dockerfile: ./workers/filter/Dockerfile
    container_name: filter-worker
    depends_on:
      - query-orchestrator
    networks:
      - orchestrator-network
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password

  aggregator-worker:
    build:
      context: ../../..
      dockerfile: ./workers/aggregator/Dockerfile
    container_name: aggregator-worker
    depends_on:
      - query-orchestrator
    networks:
      - orchestrator-network
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password

  join-worker:
    build:
      context: ../../..
      dockerfile: ./workers/join/Dockerfile
    container_name: join-worker
    depends_on:
      - query-orchestrator
    networks:
      - orchestrator-network
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password

  groupby-worker:
    build:
      context: ../../..
      dockerfile: ./workers/group_by/Dockerfile
    container_name: groupby-worker
    depends_on:
      - query-orchestrator
    networks:
      - orchestrator-network
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: password

networks:
  orchestrator-network:
    driver: bridge
  shared-network:
    external: true
